spring:
  activemq:
    broker-url: tcp://localhost:61616 # Usando PooledConnectionFactory usar este CachingConnectionFactory .
#    broker-url: failover:(tcp://localhost:61616,tcp://localhost:61617)?initialReconnectDelay=100&randomize=false # Usando PooledConnectionFactory usar este.
